# We simulate the time-development of the wave function in an N_x x N_y x N_z sized cube
# The origin of the coordinate system is in the center of the simulated volume
# We use a right-handed system, where +Y is the upward direction
# Values are given in the Hartree atomic unit system

# The naming convention is as follows: <descriptive name>_<measurement unit if any>_<vector dimension count if greater than 1>


[simulation]
method = "fourier"
order_of_approximation = 10
delta_time_h_bar_per_hartree = 0.05
total_iteration_count = 6000
is_dynamic_potential_mode = true
enable_wave_function_saving = false
wave_function_save_iteration_interval = 50
double_precision_calculation = false

[wave_packet]
particle_mass_electron_rest_mass = 1.0
initial_wp_position_bohr_radii_3 = [30.0, 0.0, 0.0]
initial_wp_velocity_bohr_radii_hartree_per_h_bar_3 = [1.5, 0.0, 0.0]
initial_wp_width_bohr_radii = 2.0

[volume]
simulated_volume_dimensions_bohr_radii_3 = [120.0, 120.0, 120.0] #Including absorbing potential regions
number_of_voxels_3 = [256, 256, 256]         #Including absorbing potential regions
observation_box_bottom_corner_bohr_radii_3 = [-45.0, -45.0, -45.0]   # Same as the inner boundary of the draining potential
observation_box_top_corner_bohr_radii_3 = [45.0, 45.0, 45.0]   # Same as the inner boundary of the draining potential

[absorbing_boundary_condition]
outer_potential_in_positive_xyz_direction_hartree_3 = [-100.0, -100.0, -100.0]
outer_potential_in_negative_xyz_direction_hartree_3 = [-100.0, -100.0, -100.0]
start_offset = 1.0
slope_exponent_in_positive_xyz_direction_3 = [3.0, 3.0, 3.0]    # e: f(x) = x^e,    x in [0, 1]
slope_exponent_in_negative_xyz_direction_3 = [3.0, 3.0, 3.0]    # e: f(x) = x^e,    x in [0, 1]
enable = true

[potential.pre_initialized_potential]
path = ""
enable = false
visible = true

[[potential.walls]]
potential_hartree = 200
center_bohr_radii_3 = [30.0, 0.0, 0.0]
normal_vector_3 = [1.0, 0.0, 0.0]
plateau_thickness_bohr_radii = 5.0
slope_thickness_bohr_radii = 0.0
slope_exponent = 1.5    # e: f(x) = x^e,    x in [0, 1]
velocity_bohr_radius_hartree_per_h_bar_3 = [0.0, 0.0, 0.0]
angular_velocity_rad_hartree_per_h_bar_3 = [0.0, 0.0, 0.0]
potential_change_rate_hartree_sqr_per_h_bar = 0.0
slit_count = 3
slit_spacing_bohr_radii = 5.0
slit_width_bohr_radii = 2.0
slit_rotation_radian = 0.0
enable = false
visible=true

[[potential.walls]]
potential_hartree = 200
center_bohr_radii_3 = [50.0, 0.0, 0.0]
normal_vector_3 = [1.0, 0.0, 0.0]
plateau_thickness_bohr_radii = 30.0
slope_thickness_bohr_radii = 2.0
slope_exponent = 1.0    # e: f(x) = x^e,    x in [0, 1]
velocity_bohr_radius_hartree_per_h_bar_3 = [0.0, 0.0, 0.0]
angular_velocity_rad_hartree_per_h_bar_3 = [0.0, 0.0, 0.0]
potential_change_rate_hartree_sqr_per_h_bar = 0.0
slit_count = 0
slit_spacing_bohr_radii = 1.0
slit_width_bohr_radii = 0.5
slit_rotation_radian = 0.0
enable = false
visible=true

#[linear_potential_gradient]
#center_bohr_radii_3 = [0.0, 40.0, 0.0]
#gradient_direction = [0.0, 1.0, 0.0]
#gradient_magnitude_hartree_per_bohr_radius = 0.25
#visible = true

[measurement.volumetric]
camera_rotation_speed = -0.5
camera_azimuth = -10.0
camera_elevation = 10.0
light_direction = [1.0, 1.0, -1.0]
light_rotation_speed = 0.001
light_elevation_speed = 0.0
animation_frame_rate = 25
animation_frame_capture_iteration_interval = 50
image_capture_iteration_interval = 100
enable_animation = false
enable_image = true

[measurement.per_axis_plot]
title = "Per-axis plot"
x_axis_label = "X axis"
y_axis_label = "Y axis"
z_axis_label = "Z axis"
potential_label = "Potential"
potential_plot_offset = -0.34
potential_plot_scale = 0.02
animation_frame_rate = 25
animation_frame_capture_iteration_interval = 50
image_capture_iteration_interval = 50
enable_animation = false
enable_image = false

[paths]
cache_dir = "./cache"
output_dir = "./output"
