# We simulate the time-development of the wave function in an NxNxN sized cube
# The origin of the coordinate system is in the center of the simulated volume
# We use a right-handed system, where +Y is the upward direction
# Values are given in the Hartree atomic unit system

["wave_packet"]
particle_mass = 1.0
initial_wp_position_bohr_radii_3 = [-15.0, 0.0, 0.0]
initial_wp_velocity_bohr_radii_hartree_per_h_bar = [0.0, 0.0, 0.0]
wp_width_bohr_radii = 2.0

["volume"]
simulated_volume_width_bohr_radii = 120.0 #Including draining potential regions
number_of_samples_per_axis = 256         #Including draining potential regions
viewing_window_boundary_bottom_corner_bohr_radii_3 = [30.0, 30.0, 30.0]   # Same as the inner boundary of the draining potential
viewing_window_boundary_top_corner_bohr_radii_3 = [-30.0, -30.0, -30.0]   # Same as the inner boundary of the draining potential

["drain"]
outer_potential_hartree = -100.0
interpolation_exponent = 3.0


[[walls]]
potential_hartree = 50
center_bohr_radii_3 = [-2.0, 0.0, 0.0]
normal_vector_3 = [1.0, 0.0, 0.0]
thickness_bohr_radii = 1.0
visible=true

[[walls]]
potential_hartree = 50
center_bohr_radii_3 = [2.0, 0.0, 0.0]
normal_vector_3 = [1.0, 0.0, 0.0]
thickness_bohr_radii = 1.0
visible=true

#[[walls]]
#potential_hartree = 20
#center_bohr_radii_3 = [30.0, 0.0, 0.0]
#normal_vector_3 = [1.0, 0.0, 0.0]
#thickness_bohr_radii = 10.0
#visible=false

#[[walls]]
#potential_hartree = 20
#center_bohr_radii_3 = [-30.0, 0.0, 0.0]
#normal_vector_3 = [1.0, 0.0, 0.0]
#thickness_bohr_radii = 10.0
#visible=false

#[[walls]]
#potential_hartree = 20
#center_bohr_radii_3 = [0.0, 0.0, 30.0]
#normal_vector_3 = [0.0, 0.0, 1.0]
#thickness_bohr_radii = 10.0
#visible=false

#[[walls]]
#potential_hartree = 20
#center_bohr_radii_3 = [0.0, 0.0, -30.0]
#normal_vector_3 = [0.0, 0.0, 1.0]
#thickness_bohr_radii = 10.0
#visible=false

#[[walls]]
#potential_hartree = 8
#center_bohr_radii_3 = [0.0, 0.0, 0.0]
#normal_vector_3 = [0.0, 1.0, 0.0]
#thickness_bohr_radii = 1.0
#visible=true

#[coulomb_potential]
#charge_density_elementary_charge_per_bohr_radius = 600.0
#center_bohr_radii_3 = [0.0, 11.0, 0.0]
#gradient_direction = [0.0, 1.0, 0.0]
#oxide_start_bohr_radii = 10
#oxide_end_bohr_radii = 11
#visible = false

#[linear_potential_gradient]
#center_bohr_radii_3 = [0.0, 40.0, 0.0]
#gradient_direction = [0.0, 1.0, 0.0]
#gradient_magnitude_hartree_per_bohr_radius = 0.25
#visible = true

[iteration]
delta_time_h_bar_per_hartree = 0.005
total_iteration_count = 3000
animation_frame_step_interval = 20
png_step_interval = 100
measurement_plane_capture_interval = 100
probability_plot_interval = 100
per_axis_probability_denisty_interval = 100
wave_function_save_interval = 100

[view]
video_frame_rate = 25
enable_visual_output = true

[view.volumetric]
camera_rotation_speed = 2.0
camera_azimuth = -10.0
camera_elevation = 10.0
light_direction = [-1.0, 1.0, 1.0]
light_rotation_speed = 0.001
light_elevation_speed = 0.0

[view.per_axis_plot]
title = "Interaction between 1D particles in harmonic oscillator"
x_axis_label = "A particle"
y_axis_label = "B particle"
z_axis_label = "C particle"
potential_label = "Potential"
potential_plot_offset = -0.34
potential_plot_scale = 0.02

[paths]
cache_dir = "./cache"
output_dir = "./output"
