# We simulate the time-development of the wave function in an NxNxN sized cube
# The origin of the coordinate system is in the center of the simulated volume
# +Y is the upward direction
# Values are given in hartree atomic unit system

["Wave_packet"]
particle_mass = 1.0
initial_wp_position_bohr_radii_3 = [0.0, 0.0, -10.0]
initial_wp_velocity_bohr_radii_hartree_per_h_bar = [0.0, 0.0, 5.0]
wp_width_bohr_radii = 1.0

["Volume"]
simulated_volume_width_bohr_radii = 60.0 #Including draining potential regions
number_of_samples_per_axis = 128         #Including draining potential regions
viewing_window_boundary_bottom_corner_bohr_radii_3 = [15.0, 15.0, 15.0]   # Same as the inner boundary of the draining potential
viewing_window_boundary_top_corner_bohr_radii_3 = [-15.0, -15.0, -15.0]   # Same as the inner boundary of the draining potential

["Potential"]
outer_drain_potential_hartree = -100000
drain_interpolation_exponent = 3.0
wall_potential_hartree = 200.0
wall_thickness_bohr_radii = 1.5
slit_width_bohr_radii = 2.0
distance_between_slits_bohr_radii = 0.5


["Iteration"]
total_iteration_count = 200
animation_frame_step_interval = 2
png_step_interval = 10
measurement_plane_capture_interval = 10
probability_plot_interval = 50
