particle_mass = 1.0
initial_wp_position_bohr_radii_3 = [15.0, 15.0, 5.0]
initial_wp_velocity_bohr_radii_hartree_per_h_bar = [0.0, 0.0, 10.0]
wp_width_bohr_radii = 1.0

simulated_volume_width_bohr_radii = 30.0
number_of_samples_per_axis = 120

animation_frame_step_interval = 1
png_step_interval = 10
measurement_plane_capture_interval = 10
probability_plot_interval = 50