# We simulate the time-development of the wave function in an NxNxN sized cube
# The origin of the coordinate system is in the center of the simulated volume
# We use a right-handed system, where +Y is the upward direction
# Values are given in Hartree atomic unit system

[wave_packet]
particle_mass = 1.0
initial_wp_position_bohr_radii_3 = [-20.0, 0.0, 0.0]
initial_wp_velocity_bohr_radii_hartree_per_h_bar = [3.0, 0.0, 0.0]
wp_width_bohr_radii = 2.0

[volume]
simulated_volume_width_bohr_radii = 120.0 #Including draining potential regions
number_of_samples_per_axis = 512         #Including draining potential regions
viewing_window_boundary_bottom_corner_bohr_radii_3 = [30.0, 30.0, 30.0]   # Same as the inner boundary of the draining potential
viewing_window_boundary_top_corner_bohr_radii_3 = [-30.0, -30.0, -30.0]   # Same as the inner boundary of the draining potential
double_precision_wave_tensor = false

[drain]
outer_potential_hartree = -100.0
interpolation_exponent = 3.0

#[pre_initialized_potential]
#path = "../wave_resources/pre_init_pot_01.npy"
#visible = true

[[double_slits]]
center_bohr_radius_3 = [0, 0, 0]
normal = [1, 0, 0]
potential_hartree = 20.0
thickness_bohr_radii = 3.0
slit_width_bohr_radii = 1.0
distance_between_slits_bohr_radii = 3.0
visible = true


[iteration]
delta_time_h_bar_per_hartree = 0.03
total_iteration_count = 2000
animation_frame_step_interval = 2
png_step_interval = 10
measurement_plane_capture_interval = 10
probability_plot_interval = 50
per_axis_probability_denisty_interval = 2
wave_function_save_interval = 2
method = "power_series"
enable_wave_function_save = false

[view]
video_frame_rate = 25
enable_visual_output = true

[view.volumetric]
camera_rotation_speed = 2.0
camera_azimuth = -10.0
camera_elevation = 45.0
light_direction = [-1.0, 1.0, 1.0]
light_rotation_speed = 0.001
light_elevation_speed = 0.0

[view.per_axis_plot]
title = "Projection of the probability density onto axes"
x_axis_label = "X-axis"
y_axis_label = "Y-axis"
z_axis_label = "Z-axis"
potential_label = "Potential"
potential_plot_offset = -0.34
potential_plot_scale = 0.02

[paths]
cache_dir = "./cache"
output_dir = "./output"
