# We simulate the time-development of the wave function in an N_x x N_y x N_z sized box
# The origin of the coordinate system is in the center of the simulated volume
# We use a right-handed system, where +Y is the upward direction
# Values are given in the Hartree atomic unit system

# The naming convention is as follows: <descriptive name>_<measurement unit if any>_<vector dimension count if greater than 1>

# Free space simulation from Web Schrödinger

[simulation]
method = "fourier"
order_of_approximation = 10
delta_time_h_bar_per_hartree = 0.2
total_iteration_count = 541
is_dynamic_potential_mode = true
enable_wave_function_saving = false
wave_function_save_iteration_interval = 1
double_precision_calculation = true

[wave_packet]
particle_mass_electron_rest_mass = 1.0
initial_position_bohr_radii_3 = [-34.015067794, 0.0, 0.0]
initial_velocity_bohr_radii_hartree_per_h_bar_3 = [0.60621943221906042757, 0.0, 0.0]
initial_standard_deviation_bohr_radii = 9.4486299429

[volume]
simulated_volume_dimensions_bohr_radii_3 = [145.13095592, 145.13095592, 145.13095592] #Including absorbing potential regions
number_of_voxels_3 = [256, 256, 256]         #Including absorbing potential regions
observation_box_bottom_corner_bohr_radii_3 = [-72.565, -72.565, -72.565]   # Same as the inner boundary of the draining potential
observation_box_top_corner_bohr_radii_3 = [72.565, 72.565, 72.565]   # Same as the inner boundary of the draining potential

[absorbing_boundary_condition]
outer_potential_in_positive_xyz_direction_hartree_3 = [-100.0, -10.0, -10.0]
outer_potential_in_negative_xyz_direction_hartree_3 = [-100.0, -10.0, -10.0]
start_offset = 1.0
slope_exponent_in_positive_xyz_direction_3 = [3.0, 3.0, 3.0]    # e: f(x) = x^e,    x in [0, 1]
slope_exponent_in_negative_xyz_direction_3 = [3.0, 3.0, 3.0]    # e: f(x) = x^e,    x in [0, 1]
enable = false

[potential.pre_initialized_potential]
path = ""
enable = false
visible = true

[[potential.walls]]
potential_hartree = 200
center_bohr_radii_3 = [10.0, 0.0, 0.0]
normal_vector_3 = [1.0, 0.0, 0.0]
plateau_thickness_bohr_radii = 10.0
slope_thickness_bohr_radii = 0.0
slope_exponent = 1.5    # e: f(x) = x^e,    x in [0, 1]
velocity_bohr_radius_hartree_per_h_bar_3 = [0.0, 0.0, 0.0]
angular_velocity_rad_hartree_per_h_bar_3 = [0.0, 0.0, 0.0]
potential_change_rate_hartree_sqr_per_h_bar = 0.0
slit_count = 3
slit_spacing_bohr_radii = 5.0
slit_width_bohr_radii = 2.0
slit_rotation_radian = 0.0
enable = false
visible=true

[[potential.walls]]
potential_hartree = 200
center_bohr_radii_3 = [50.0, 0.0, 0.0]
normal_vector_3 = [1.0, 0.0, 0.0]
plateau_thickness_bohr_radii = 30.0
slope_thickness_bohr_radii = 2.0
slope_exponent = 1.0    # e: f(x) = x^e,    x in [0, 1]
velocity_bohr_radius_hartree_per_h_bar_3 = [0.0, 0.0, 0.0]
angular_velocity_rad_hartree_per_h_bar_3 = [0.0, 0.0, 0.0]
potential_change_rate_hartree_sqr_per_h_bar = 0.0
slit_count = 0
slit_spacing_bohr_radii = 1.0
slit_width_bohr_radii = 0.5
slit_rotation_radian = 0.0
enable = false
visible=true

#[linear_potential_gradient]
#center_bohr_radii_3 = [0.0, 40.0, 0.0]
#gradient_direction = [0.0, 1.0, 0.0]
#gradient_magnitude_hartree_per_bohr_radius = 0.25
#visible = true

[measurement.volumetric]
camera_rotation_speed = -0.5
camera_azimuth = -10.0
camera_elevation = 10.0
light_direction = [1.0, 1.0, -1.0]
light_rotation_speed = 0.001
light_elevation_speed = 0.0
animation_frame_rate = 25
animation_frame_capture_iteration_interval = 50
image_capture_iteration_interval = 5
enable_animation = false
enable_image = false

[measurement.per_axis_plot]
title = "Per-axis plot"
x_axis_label = "X axis"
y_axis_label = "Y axis"
z_axis_label = "Z axis"
potential_label = "Potential"
potential_plot_offset = -0.34
potential_plot_scale = 0.02
animation_frame_rate = 25
animation_frame_capture_iteration_interval = 50
image_capture_iteration_interval = 100
enable_animation = false
enable_image = false

[measurement.expected_location]
enable_image = true

[[measurement.volume_probabilities]]
name = "First half"
bottom_corner_bohr_radii_3 = [-45.0, -45.0, -45.0]
top_corner_bohr_radii_3 = [0.0, 45.0, 45.0]
enable_image = false

[[measurement.volume_probabilities]]
name = "Second half"
bottom_corner_bohr_radii_3 = [0.0, -45.0, -45.0]
top_corner_bohr_radii_3 = [45.0, 45.0, 45.0]
enable_image = false

[[measurement.plane_probability_currents]]
name = "First plane"
center_bohr_radii_3 = [-5.6691779657, 0.0, 0.0]
normal_vector_3 = [1.0, 0.0, 0.0]
size_bohr_radii_2 = [145.13, 145.13]
resolution_2 = [256, 256]
enable_image = true

[[measurement.plane_probability_currents]]
name = "Middle"
center_bohr_radii_3 = [0.0, 0.0, 0.0]
normal_vector_3 = [1.0, 0.0, 0.0]
size_bohr_radii_2 = [145.13, 145.13]
resolution_2 = [256, 256]
enable_image = true

[[measurement.plane_probability_currents]]
name = "Second plane"
center_bohr_radii_3 = [7.3699313555, 0.0, 0.0]
normal_vector_3 = [1.0, 0.0, 0.0]
size_bohr_radii_2 = [145.13, 145.13]
resolution_2 = [256, 256]
enable_image = true

[paths]
cache_dir = "./cache"
output_dir = "./output"
